"""Add no_of_pages and updated pages to custom_pages in print_request table for better understandability

Revision ID: 125d9370f070
Revises: 44cea6ade956
Create Date: 2025-06-28 12:30:54.674582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '125d9370f070'
down_revision: Union[str, Sequence[str], None] = '44cea6ade956'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('print_request', sa.Column('custom_pages', sa.String(length=50), nullable=False))
    op.add_column('print_request', sa.Column('no_of_pages', sa.Integer(), nullable=False))
    op.drop_column('print_request', 'pages')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('print_request', sa.Column('pages', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('print_request', 'no_of_pages')
    op.drop_column('print_request', 'custom_pages')
    # ### end Alembic commands ###
