"""Updated file_path length

Revision ID: 27102ecdd375
Revises: 0130cb4244ef
Create Date: 2025-06-27 15:29:53.461714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27102ecdd375'
down_revision: Union[str, Sequence[str], None] = '0130cb4244ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('print_request', 'file_path',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=550),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('print_request', 'file_path',
               existing_type=sa.String(length=550),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###
