"""Add PrintFile table and relationship

Revision ID: 44cea6ade956
Revises: 27102ecdd375
Create Date: 2025-06-28 11:23:42.822656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44cea6ade956'
down_revision: Union[str, Sequence[str], None] = '27102ecdd375'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('print_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('print_request_id', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.String(length=550), nullable=False),
    sa.ForeignKeyConstraint(['print_request_id'], ['print_request.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_print_files_id'), 'print_files', ['id'], unique=False)
    op.drop_column('print_request', 'file_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('print_request', sa.Column('file_path', sa.VARCHAR(length=550), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_print_files_id'), table_name='print_files')
    op.drop_table('print_files')
    # ### end Alembic commands ###
